### ISSUE TITLE
Patching fails with message (Patch is indented 4 spaces.)

### ISSUE THREAD

**Issue by MaxOfLondon** [adamchainz/patchy#478]
### Python Version

Python 3.10.12

### Package Version

2.8.0

### Description

Trying to patch `pygame_gui.core.utility` method with simple patch needed for a test. The patching fails with "(Patch is indented 4 spaces.)" message but there were no whitespace before `def` in both `before.py` and `after.py`.

The patching code was:
```python
patchy.patch(
    pygame_gui.core.utility.create_resource_path,
    """\
    @@ -11,5 +11,5 @@
         base_path = sys._MEIPASS  # pylint: disable=no-member,protected-access
     except AttributeError:
         base_path = os.path.abspath(".")
-
+    print("!!!!!!!!!")
     return os.path.join(base_path, relative_path)""",
)
```
The output was:
```sh
Traceback (most recent call last):
  File "/home/dev/Documents/dev/python/sudoku/main.py", line 37, in <module>
    patchy.patch(
  File "/home/dev/Documents/dev/python/sudoku/.venv/lib/python3.10/site-packages/patchy/api.py", line 38, in patch
    _do_patch(func, patch_text, forwards=True)
  File "/home/dev/Documents/dev/python/sudoku/.venv/lib/python3.10/site-packages/patchy/api.py", line 103, in _do_patch
    new_source = _apply_patch(source, patch_text, forwards, func.__name__)
  File "/home/dev/Documents/dev/python/sudoku/.venv/lib/python3.10/site-packages/patchy/api.py", line 155, in _apply_patch
    raise ValueError(msg)
ValueError: Could not apply the patch to 'create_resource_path'. The message from `patch` was:
(Patch is indented 4 spaces.)
patching file /tmp/patchyjphki7ve/create_resource_path.py
Hunk #1 FAILED at 11.
1 out of 1 hunk FAILED -- saving rejects to file /tmp/patchyjphki7ve/create_resource_path.py.rej
```

The code to patch was:
```python
def create_resource_path(relative_path: Union[str, Path]):
    """
    Get absolute path to resource, works for dev and for PyInstaller's 'onefile' mode

    :param relative_path: A relative path to a file of some kind.

    """

    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS  # pylint: disable=no-member,protected-access
    except AttributeError:
        base_path = os.path.abspath(".")

    return os.path.join(base_path, relative_path)
```

Neither `before.py` nor `after.py` defs were indented.

The diff was:
```sh
$ diff -u before.py after.py 
--- before.py   2023-08-09 21:37:30.532080125 +0100
+++ after.py    2023-08-09 22:08:21.448118156 +0100
@@ -11,5 +11,5 @@
         base_path = sys._MEIPASS  # pylint: disable=no-member,protected-access
     except AttributeError:
         base_path = os.path.abspath(".")
-
+    print("!!!!!!!!!")
     return os.path.join(base_path, relative_path)
```

**Comment by MaxOfLondon** [comment]
Turns out that this is just documentation error. 
The documentation shows:
```python
The filenames are not necessary for patchy to work. Take only from the first @@ line onwards into the multiline string you pass to patchy.patch():

patchy.patch(
    foo,
    """\
    @@ -1,2 +1,2 @@
     def foo():
    -    print("Change me")
    +    print("Changed")
    """,
)
```
but the @@ needs to be undented as well for this to work.
Thank you creating great util and for correcting documentation in advance!

**Comment by adamchainz** [comment]
Thanks for following up on your ticket with your solution, by the way. Very helpful!
